import * as THREE from 'three';

export const HARDWARE_DEFINITIONS = {
  robot: {
    id: 'robot',
    file: 'assets/chassis.glb',
    title: 'BERRYBOT // TRACKED ROBOTICS PLATFORM',
    eyebrow: 'PHYSICAL 3D MODEL // SOLIDWORKS ASSEMBLY',
    category: 'AUTONOMOUS ROBOTICS',
    summary: 'A tracked autonomous robotics platform designed and built entirely by Jaijitesh around a Waveshare ESP32 controller. Features encoder-based motion control, S-curve trajectory profiling, telemetry, path tracking, and return-to-home capabilities.',
    specs: [
      ['CONTROLLER', 'Waveshare ESP32 Multi-Channel Driver'],
      ['KINEMATICS', 'Differential Track Drive w/ S-Curve Smoothing'],
      ['FEEDBACK', 'Optical Quadrature Encoders + Telemetry Loop'],
      ['CAPABILITIES', 'Path Tracking, Return-To-Home, Closed-Loop PID'],
      ['EXPANSION', 'Engineered to integrate Vision, Navigation, & WindSim'],
      ['SOURCE', 'SolidWorks CAD Assembly (TV_ensemble / M4)'],
    ],
    scale: 0.88,
    isGroundedOnFloor: false,
    benchPosition: new THREE.Vector3(-1.38, 0.85, 0.05),
    benchRotation: new THREE.Euler(0, 0.32, 0),
  },
  camera: {
    id: 'camera',
    file: 'assets/canon_at-1_retro_camera.glb',
    title: 'CANON AT-1 // 35MM RETRO OPTICS',
    eyebrow: 'PHYSICAL 3D MODEL // COMPUTER VISION & SENSING',
    category: 'OPTICAL SENSING',
    summary: 'Retro 35mm SLR optical camera body representing computer vision, photogrammetry data synthesis pipelines, and spectral chromaticity research.',
    specs: [
      ['MOUNT', 'Canon FD Bayonet System'],
      ['ROLE', 'Optical Perception & Image Processing Asset'],
      ['SHUTTER', 'Focal-Plane Electronic Shutter'],
      ['RESEARCH LINK', 'Spectral Color-Space & Data Generation'],
    ],
    scale: 0.42,
    isGroundedOnFloor: false,
    benchPosition: new THREE.Vector3(-0.82, 0.85, 0.22),
    benchRotation: new THREE.Euler(0, 0.45, 0),
  },
  raspberry: {
    id: 'raspberry',
    file: 'assets/raspberry.glb',
    title: 'RASPBERRY PI 4 // MODEL B',
    eyebrow: 'PHYSICAL 3D MODEL // SINGLE-BOARD COMPUTER',
    category: 'EDGE COMPUTE NODE',
    summary: 'High-performance edge computational node for on-board autonomous robot processing, local vision pipeline orchestration, and system telemetry logging.',
    specs: [
      ['SOC', 'Broadcom BCM2711 Quad-core Cortex-A72 @ 1.5GHz'],
      ['MEMORY', '4GB LPDDR4-3200 SDRAM'],
      ['IO PORTS', '2x USB 3.0, 2x USB 2.0, Gigabit Ethernet, Dual Micro-HDMI'],
      ['GPIO', 'Standard 40-Pin Header (I2C, SPI, UART, PWM)'],
      ['ROLE', 'Edge Vision & High-Level Autonomy Coordinator'],
    ],
    scale: 0.36,
    isGroundedOnFloor: false,
    benchPosition: new THREE.Vector3(0.92, 0.85, 0.22),
    benchRotation: new THREE.Euler(0, -0.22, 0),
  },
  esp32: {
    id: 'esp32',
    file: 'assets/esp32.glb',
    title: 'ESP32-WROOM // DUAL-CORE MICROCONTROLLER',
    eyebrow: 'PHYSICAL 3D MODEL // EMBEDDED HARDWARE',
    category: 'MICROCONTROLLER & MOTOR CONTROL',
    summary: 'High-speed 240MHz dual-core embedded processor driving low-latency motor control loops, real-time optical encoder counting, and hardware sensor telemetry.',
    specs: [
      ['MCU', 'ESP-WROOM-32 (Tensilica Xtensa Dual-Core 240MHz)'],
      ['TIMING', 'Hardware Timers for 20kHz Motor PWM Generation'],
      ['PULSE COUNT', 'Hardware PCNT Peripheral for Encoder Ranging'],
      ['CONNECTIVITY', '2.4 GHz Wi-Fi & Bluetooth v4.2 BR/EDR/BLE'],
      ['ROLE', 'Low-Level Real-Time Motor & Sensor Controller'],
    ],
    scale: 0.16,
    isGroundedOnFloor: false,
    benchPosition: new THREE.Vector3(1.22, 0.85, 0.22),
    benchRotation: new THREE.Euler(0, -0.32, 0),
  },
  cat: {
    id: 'cat',
    file: 'assets/3d_modelling_my_cat_fripouille.glb',
    title: 'CRISPY // PET CAT',
    eyebrow: 'EASTER EGG // CRISPY',
    category: 'PET',
    summary: 'Crispy the pet cat resting on the workbench.',
    specs: [
      ['SPECIES', 'Domestic Cat'],
      ['NAME', 'Crispy'],
    ],
    scale: 0.72,
    isGroundedOnFloor: false,
    benchPosition: new THREE.Vector3(1.42, 0.85, -0.32),
    benchRotation: new THREE.Euler(0, -0.65, 0),
  },
  dog: {
    id: 'dog',
    file: 'assets/full_body_shepherd_dog_meshy.glb',
    title: 'BERRY // PET DOG',
    eyebrow: 'EASTER EGG // BERRY',
    category: 'PET',
    summary: 'Berry the pet dog beside the workbench.',
    specs: [
      ['BREED', 'Belgian Malinois'],
      ['NAME', 'Berry'],
    ],
    scale: 0.92,
    isGroundedOnFloor: true,
    benchPosition: new THREE.Vector3(-1.62, 0, 1.05),
    benchRotation: new THREE.Euler(0, 0.45, 0),
  },
  telescope: {
    id: 'telescope',
    file: 'assets/telescope.glb',
    title: 'REFRACTOR TELESCOPE // ASTRONOMICAL OPTICS',
    eyebrow: 'PHYSICAL 3D MODEL // SCIENTIFIC INSTRUMENT',
    category: 'SCIENTIFIC COMPUTING',
    summary: 'Precision equatorial refractor telescope standing right beside the workbench, symbolizing celestial observation, mathematical modeling, and scientific computing.',
    specs: [
      ['OPTICS', 'Achromatic Refractor Objective'],
      ['MOUNT', 'Heavy-Duty Equatorial Tripod'],
      ['ROLE', 'Scientific Instrumentation & Horizon Exploration'],
    ],
    scale: 1.85,
    isGroundedOnFloor: true,
    benchPosition: new THREE.Vector3(2.08, 0, 0.38), // Right next to the table
    benchRotation: new THREE.Euler(0, -0.65, 0),
  }
};
